region_codes = {'Eastern England': 10,
                'East Midlands': 11,
                'London': 12,
                'Merseyside and Northern Wales': 13,
                'West Midlands': 14,
                'North Eastern England': 15,
                'North Western England': 16,
                'Northern Scotland': 17,
                'Southern Scotland': 18,
                'South Eastern England': 19,
                'Southern England': 20,
                'Southern Wales': 21,
                'South Western England': 22,
                'Yorkshire': 23}

region_names = {'10': 'Eastern England',
                '11': 'East Midlands',
                '12': 'London',
                '13': 'Merseyside and Northern Wales',
                '14': 'West Midlands',
                '15': 'North Eastern England',
                '16': 'North Western England',
                '17': 'Northern Scotland',
                '18': 'Southern Scotland',
                '19': 'South Eastern England',
                '20': 'Southern England',
                '21': 'Southern Wales',
                '22': 'South Western England',
                '23': 'Yorkshire'}